/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import junit.framework.Assert;

import org.junit.Test;


import static org.junit.Assert.*;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'",
				classUnderTest.someLibraryMethod());
	}

	@Test
	public void testEdad() {
		Main m = new Main();
		Assert.assertEquals("Error al comparar", m.edad("04/12/1996"),
				"La edad es: 20 años,5 meses, 26 días");
	}
	@Test
	public void testEdadNeg() {
		Main m = new Main();
		Assert.assertEquals("Error al comparar", m.edad("04/10/1996"),
				"La edad es: 20 años,5 meses, 26 días");
	}
	@Test
	public void testPrimo() {
		Main m = new Main();
		Assert.assertEquals("Error al comparar", m.primo(7),
				"true");
	}
	@Test
	public void testPrimoNeg() {
		Main m = new Main();
		Assert.assertEquals("Error al comparar", m.primo(0),
				"false");
	}
	@Test
	public void testPers() {
		Main m = new Main();
		Persona a = new Persona("a","estudiante",18);
		Persona b = new Persona("b","abogado",20);
		Assert.assertEquals("Error al comparar", m.aplica(a,b,"estudiante"),
				"a");
	}
	@Test
	public void testPers1() {
		Main m = new Main();
		Persona a = new Persona("a","estudiante",18);
		Persona b = new Persona("b","estudiante",20);
		Assert.assertEquals("Error al comparar", m.aplica(a,b,"estudiante"),
				"b");
	}
	@Test
	public void testPers2() {
		Main m = new Main();
		Persona a = new Persona("a","estudiante",20);
		Persona b = new Persona("b","estudiante",20);
		Assert.assertEquals("Error al comparar", m.aplica(a,b,"estudiante"),
				"a");
	}

}
