import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    
}




